### ISSUE TITLE
How to set up an own signal hub server?

### ISSUE THREAD

**Issue by s-a** [substack/chatwizard#4]

**Comment by Flet** [comment]
Use this: https://github.com/mafintosh/signalhub

**Comment by s-a** [comment]
pretty cool

**Comment by s-a** [comment]
Any example server side code available that handshakes with chatwizzard? It seems it' s not trivial. :scream:

**Comment by s-a** [comment]
I d like to know whats going on at signalhub.mafintosh.com :laughing:

**Comment by Flet** [comment]
That is what is so cool about chatwizard... there is no server!

Signalhub is:
> a Simple signaling server that can be used to coordinate handshaking with webrtc or other fun stuff.

So once that handshaking happens, the signaling server is done with its job. The clients themselves would form a "swarm" and propagate messages to each other without a central server. Pretty sweet!

Another example of P2P chat is http://moose-team.github.io/friends/ which uses similar components to chatwizard.

**Comment by s-a** [comment]
I like the chatwizard approach more... :smile:   Just tried to setup signal server local. but failed. If I start the client it errors requesting ```http://localhost/v1/2e55365a6a6aeabdd9f74bac9e6dcb78520e318a/all```. So far I have no idea to set up a server . As far as I can see the client connects with ```var hub = signalhub(shasum('chatwizard.' + channel), self.hubs)```. Any chance to get source from https://github.com/mafintosh/signalhub so that I can learn from code what is going on there?
